apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: community-web
  labels:
    app: community-web
spec:
  selector:
    matchLabels:
      app: community-web
  replicas: 1
  template:
    metadata:
      labels:
        app: community-web
    spec:
      containers:
      - name: community-web
        image: errrrk/community-web
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
